# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Build and Test

on: [ pull_request]

jobs:
  build:
    name: Java ${{ matrix.java }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        java: [8, 11, 16]
    steps:
    - uses: actions/checkout@v2
    - name: Cache Local Maven Repository
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    - name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v2
      with:
        java-version: ${{ matrix.java }}
        distribution: 'adopt'
    - name: Build, Test, and Package
      run: mvn -B -Dliquibase.version.qualifier=${{ github.head_ref }} -Dbuild.number=${{ github.run_number }} -Dbuild.commit=${{ github.sha }} clean test package
    - name: Archive Test Results
      if: ${{ always() }}
      uses: actions/upload-artifact@v2
      with:
        name: liquibase-test-results-jdk${{ matrix.java }}
        path: ./**/target/surefire-reports

    - name: Archive artifacts
      if: ${{ matrix.java == 8}}
      uses: actions/upload-artifact@v2
      with:
        name: liquibase-artifacts-${{ github.head_ref }}
        path: |
          liquibase-dist/target/liquibase-0-${{ github.head_ref }}-SNAPSHOT.tar.gz
          liquibase-dist/target/liquibase-0-${{ github.head_ref }}-SNAPSHOT.jar
          liquibase-maven-plugin/target/liquibase-0-${{ github.head_ref }}-SNAPSHOT.jar
          liquibase-cdi/target/liquibase-0-${{ github.head_ref }}-SNAPSHOT.jar
          target/liquibase-0-${{ github.head_ref }}-SNAPSHOT-javadoc
    - name: Archive build
      if: ${{ matrix.java == 8}}
      uses: actions/upload-artifact@v2
      with:
        name: liquibase-build-${{ github.head_ref }}
        path: |
          **/target/*-0-${{ github.head_ref }}-SNAPSHOT.jar
          **/target/test-classes

  integration-test:
    name: Integration Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache Local Maven Repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: Download Artifacts
        uses: actions/download-artifact@v2
        with:
          path: liquibase-build-${{ github.head_ref }}

      - name: Login to Artifactory
        uses: docker/login-action@v1
        with:
          registry: docker-dev.artifactory.datical.net
          username: ${{ secrets.RT_USER }}
          password: ${{ secrets.RT_TOKEN }}
      - name: Start Docker Databases
        run: docker-compose -f ./liquibase-integration-tests/docker/docker-compose.yml up -d
      - name: Run Tests
        run: mvn -B -Dliquibase.version.qualifier=${{ github.head_ref }} surefire:test
      - name: Stop Docker Databases
        run: docker-compose -f ./liquibase-integration-tests/docker/docker-compose.yml down
      - name: Archive Test Results
        if: ${{ always() }}
        uses: actions/upload-artifact@v2
        with:
          name: test-reports-integration
          path: |
              ./**/target/surefire-reports
