# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Build and Test

on: [ pull_request]

jobs:
  test:
    name: Java ${{ matrix.java }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        java: [8, 11, 16]
    steps:
    - uses: actions/checkout@v2
    - name: Cache Local Maven Repository
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    - name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v2
      with:
        java-version: ${{ matrix.java }}
        distribution: 'adopt'
    - name: Test and Package
      run: mvn -B -Dliquibase.version.qualifier=${{ github.head_ref }} -Dbuild.number=${{ github.run_number }} -Dbuild.commit=${{ github.sha }} test package
    - name: Archive Test Results
      if: ${{ always() }}
      uses: actions/upload-artifact@v2
      with:
        name: liquibase-test-results-jdk${{ matrix.java }}
        path: ./**/target/surefire-reports
    - name: Archive liquibase.zip
      if: ${{ matrix.java == 8}}
      uses: actions/upload-artifact@v2
      with:
        name: artifacts
        path: liquibase-dist/target/liquibase-*.SNAPSHOT.zip
    - name: Archive liquibase-maven-plugin.zip
      if: ${{ matrix.java == 8}}
      uses: actions/upload-artifact@v2
      with:
        name: artifacts
        path: liquibase-maven-plugin/target/liquibase-*.SNAPSHOT.jar
    - name: Archive liquibase-maven-plugin.zip
      if: ${{ matrix.java == 8}}
      uses: actions/upload-artifact@v2
      with:
        name: artifacts
        path: liquibase-cdi/target/liquibase-*.SNAPSHOT.jar
