# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Package

on:
  workflow_dispatch:
#    inputs:
#      headSha:
#        description: 'Head SHA'
#        required: true
#      headRef:
#        description: 'Head Ref'
#        required: true

jobs:
  package:
    name: Build Packages
    runs-on: ubuntu-latest
    steps:
      - name: Mark Status As Pending
        id: create-check
        uses: actions/github-script@v4
        with:
          script: |
            await repos.createCommitStatus({
              "owner": "liquibase",
              "repo": "liquibase",
              "context": "build-artifacts",
              "description": "Build Artifacts",
              "sha": "${{ github.sha }}",
              "status": "pending",
              "target_url": "https://github.com/liquibase/liquibase/actions/runs/${{ github.run_id }}"
            });

      - uses: actions/checkout@v2
#        with:
#          ref: ${{ context.payload.inputs.headSha }}

      - name: Cache Local Maven Repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'

      - name: Download liquibase modules
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: build.yml
          workflow_conclusion: success
#          branch: ${{ github.event.workflow_run.head_branch }}
          name: liquibase-modules
          path: download

      - name: Install Built Modules
        run: |
          (cd download && find . -name *-SNAPSHOT.jar -exec mvn -B org.apache.maven.plugins:maven-install-plugin:3.0.0-M1:install-file -Dfile={} \;)
          (cd download && find . -name *-SNAPSHOT-sources.jar -exec mvn -B org.apache.maven.plugins:maven-install-plugin:3.0.0-M1:install-file -Dfile={} \;)

      - name: Build Final Jar & Tar/Zips
        run: mvn -B -pl liquibase-dist package

      - name: Archive Packages
        uses: actions/upload-artifact@v2
        with:
          name: liquibase-packages
          path: |
            liquibase-dist/target/liquibase-0-SNAPSHOT.tar.gz
            liquibase-dist/target/liquibase-0-SNAPSHOT.zip
            liquibase-dist/target/liquibase-0-SNAPSHOT.jar
            liquibase-maven-plugin/target/liquibase-maven-plugin-0-SNAPSHOT.jar
            liquibase-cdi/target/liquibase-cdi-0-SNAPSHOT.jar

      - name: Update Status Check
        uses: actions/github-script@v4
        if: always()
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            await repos.createCommitStatus({
              "owner": "liquibase",
              "repo": "liquibase",
              "context": "build-artifacts",
              "description": "Build Artifacts",
              "sha": "${{ github.sha }}",
              "status": "${{ job.status }}",
              "target_url": "https://github.com/liquibase/liquibase/actions/runs/${{ github.run_id }}"
            });
