# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Package

on: [ pull_request]

jobs:
  package:
    name: Build Packages
    runs-on: ubuntu-latest
    steps:
      - name: Wait for build to finish
        uses: fountainhead/action-wait-for-check@v1.0.0
        id: wait-for-build
        with:
          token: ${{ secrets.BOT_TOKEN }}
          checkName: build
          ref: ${{ github.event.pull_request.head.sha || github.sha }}

      - name: Check build status
        if: steps.wait-for-build.outputs.conclusion != 'success'
        uses: actions/github-script@v3
        with:
          script: |
            core.setFailed('Build failed: ${{ steps.wait-for-build.outputs.conclusion }}')

      - uses: actions/checkout@v2
      - name: Cache Local Maven Repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: Restore Built Code Cache
        uses: actions/cache@v2
        with:
          key: built-code-${{ github.sha }}
          path: ./**/target
      - name: Install pre-built modules
        run: mvn -B -pl "!liquibase-dist" jar:jar install:install
      - name: Build Final Jar & Tar/Zips
        run: mvn -B -pl liquibase-dist package

      - name: Archive Packages
        uses: actions/upload-artifact@v2
        with:
          name: liquibase-packages
          path: |
            liquibase-dist/target/liquibase-0-SNAPSHOT.tar.gz
            liquibase-dist/target/liquibase-0-SNAPSHOT.zip
            liquibase-dist/target/liquibase-0-SNAPSHOT.jar
            liquibase-maven-plugin/target/liquibase-maven-plugin-0-SNAPSHOT.jar
            liquibase-cdi/target/liquibase-cdi-0-SNAPSHOT.jar
